// ── Additional Critical Date Rows ─────────────────────────────────────────────
// Spread into the ROWS array in critical-dates-page.tsx
// monthsOut is relative to Sep 2026 (app's "today")

export const ADDITIONAL_CRITICAL_DATES = [

  // ── Empire State Building (cd-esb-1 through cd-esb-5) ────────────────────
  {
    id: "cd-esb-1", asset: "Empire State Building", tenant: "PVH Corp", suite: "Suite 3001",
    sf: 21000, dateType: "Expiring" as const, urgency: "Critical" as const,
    date: "Dec 31, 2026", dateSortable: 20261231, monthsOut: 3,
    noticePeriod: "12 months", noticeDeadline: "Dec 31, 2025",
    responsible: "Asset Manager", leaseId: "l29",
    notes: "Tenant considering relocation to Midtown South. LOI expected by Oct.",
    draftAction: "Draft renewal proposal",
    status: "Awaiting response" as const, activityLog: [],
  },
  {
    id: "cd-esb-2", asset: "Empire State Building", tenant: "Marsh & McLennan", suite: "Suite 2501",
    sf: 20000, dateType: "Notice" as const, urgency: "Critical" as const,
    date: "Oct 15, 2026", dateSortable: 20261015, monthsOut: 1,
    noticePeriod: "6 months", noticeDeadline: "Oct 15, 2026",
    responsible: "Asset Manager", leaseId: "l31",
    notes: "Notice period deadline to exercise renewal option. Must confirm intent.",
    draftAction: "Draft notice letter",
    status: "Pending" as const, activityLog: [],
  },
  {
    id: "cd-esb-3", asset: "Empire State Building", tenant: "Verizon", suite: "Suite 3201",
    sf: 22000, dateType: "Renewal" as const, urgency: "Upcoming" as const,
    date: "Nov 15, 2026", dateSortable: 20261115, monthsOut: 2,
    noticePeriod: "6 months", noticeDeadline: "Sep 30, 2026",
    responsible: "Asset Manager", leaseId: "l28",
    notes: "Renewal negotiation underway. Tenant requesting 5-year term at market.",
    draftAction: undefined,
    status: "Notice sent" as const, activityLog: [],
  },
  {
    id: "cd-esb-4", asset: "Empire State Building", tenant: "PwC", suite: "Suite 2001",
    sf: 21000, dateType: "TI deadline" as const, urgency: "Upcoming" as const,
    date: "Feb 28, 2027", dateSortable: 20270228, monthsOut: 5,
    noticePeriod: "N/A", noticeDeadline: undefined,
    responsible: "Property Manager", leaseId: "l32",
    notes: "TI work must be completed before lease expiry. Contractor bids due Nov.",
    draftAction: "Draft TI scope letter",
    status: "Pending" as const, activityLog: [],
  },
  {
    id: "cd-esb-5", asset: "Empire State Building", tenant: "Citi", suite: "Suite 2801",
    sf: 20000, dateType: "Option" as const, urgency: "Upcoming" as const,
    date: "Mar 31, 2027", dateSortable: 20270331, monthsOut: 6,
    noticePeriod: "9 months", noticeDeadline: "Sep 30, 2026",
    responsible: "Asset Manager", leaseId: "l30",
    notes: "Renewal option exercise window. Tenant to confirm within 90 days.",
    draftAction: undefined,
    status: "Pending" as const, activityLog: [],
  },

  // ── Salesforce Tower (cd-sf-1 through cd-sf-5) ────────────────────────────
  {
    id: "cd-sf-1", asset: "Salesforce Tower", tenant: "Lyft", suite: "Suite 2801",
    sf: 20000, dateType: "Expiring" as const, urgency: "Critical" as const,
    date: "Nov 30, 2026", dateSortable: 20261130, monthsOut: 2,
    noticePeriod: "12 months", noticeDeadline: "Nov 30, 2025",
    responsible: "Asset Manager", leaseId: "l36",
    notes: "Lyft exploring subleasing options. Relocation risk is high.",
    draftAction: "Draft sublease consent framework",
    status: "Awaiting response" as const, activityLog: [],
  },
  {
    id: "cd-sf-2", asset: "Salesforce Tower", tenant: "Snap Inc.", suite: "Suite 2201",
    sf: 18000, dateType: "Notice" as const, urgency: "Upcoming" as const,
    date: "Jan 15, 2027", dateSortable: 20270115, monthsOut: 4,
    noticePeriod: "6 months", noticeDeadline: "Jan 31, 2027",
    responsible: "Asset Manager", leaseId: "l38",
    notes: "Renewal notice window opens Jan. Tenant requested term sheet.",
    draftAction: "Draft renewal term sheet",
    status: "Pending" as const, activityLog: [],
  },
  {
    id: "cd-sf-3", asset: "Salesforce Tower", tenant: "OpenAI", suite: "Suite 2001",
    sf: 20000, dateType: "Rent commencement" as const, urgency: "Critical" as const,
    date: "Oct 1, 2026", dateSortable: 20261001, monthsOut: 1,
    noticePeriod: "N/A", noticeDeadline: undefined,
    responsible: "Property Manager", leaseId: "l39",
    notes: "Annual rent step-up commences. Confirm billing update with finance.",
    draftAction: "Draft commencement letter",
    status: "Pending" as const, activityLog: [],
  },
  {
    id: "cd-sf-4", asset: "Salesforce Tower", tenant: "Microsoft", suite: "Suite 1001",
    sf: 22000, dateType: "Option" as const, urgency: "Monitoring" as const,
    date: "Mar 1, 2028", dateSortable: 20280301, monthsOut: 18,
    noticePeriod: "12 months", noticeDeadline: "Mar 1, 2027",
    responsible: "Asset Manager", leaseId: "l41",
    notes: "Expansion option exercisable Mar 2028. Monitor tenant growth plans.",
    draftAction: undefined,
    status: "Pending" as const, activityLog: [],
  },
  {
    id: "cd-sf-5", asset: "Salesforce Tower", tenant: "Adobe Systems", suite: "Suite 2401",
    sf: 22000, dateType: "Inspection" as const, urgency: "Critical" as const,
    date: "Oct 1, 2026", dateSortable: 20261001, monthsOut: 1,
    noticePeriod: "N/A", noticeDeadline: undefined,
    responsible: "Property Manager", leaseId: "l37",
    notes: "Annual building systems inspection per lease terms. Schedule with tenant.",
    draftAction: undefined,
    status: "Pending" as const, activityLog: [],
  },

  // ── One Financial Plaza (cd-ofp-1 through cd-ofp-4) ──────────────────────
  {
    id: "cd-ofp-1", asset: "One Financial Plaza", tenant: "State Street Corp", suite: "Suite 1501",
    sf: 8500, dateType: "Expiring" as const, urgency: "Upcoming" as const,
    date: "Aug 31, 2027", dateSortable: 20270831, monthsOut: 11,
    noticePeriod: "12 months", noticeDeadline: "Aug 31, 2026",
    responsible: "Asset Manager", leaseId: "l44",
    notes: "Renewal discussions started. Tenant evaluating right-sizing options.",
    draftAction: "Draft renewal proposal",
    status: "Notice sent" as const, activityLog: [],
  },
  {
    id: "cd-ofp-2", asset: "One Financial Plaza", tenant: "Liberty Mutual", suite: "Suite 1301",
    sf: 9000, dateType: "Option" as const, urgency: "Upcoming" as const,
    date: "Jun 1, 2027", dateSortable: 20270601, monthsOut: 9,
    noticePeriod: "9 months", noticeDeadline: "Sep 1, 2026",
    responsible: "Asset Manager", leaseId: "l45",
    notes: "Renewal option window opens Jun 2027. Tenant likely to exercise.",
    draftAction: undefined,
    status: "Pending" as const, activityLog: [],
  },
  {
    id: "cd-ofp-3", asset: "One Financial Plaza", tenant: "John Hancock", suite: "Suite 1101",
    sf: 7500, dateType: "Notice" as const, urgency: "Critical" as const,
    date: "Nov 1, 2026", dateSortable: 20261101, monthsOut: 2,
    noticePeriod: "6 months", noticeDeadline: "Nov 1, 2026",
    responsible: "Asset Manager", leaseId: "l46",
    notes: "Tenant must provide renewal intent notice by Nov 1.",
    draftAction: "Draft notice letter",
    status: "Pending" as const, activityLog: [],
  },
  {
    id: "cd-ofp-4", asset: "One Financial Plaza", tenant: "Wellington Mgmt", suite: "Suite 0801",
    sf: 7400, dateType: "Renewal" as const, urgency: "Monitoring" as const,
    date: "May 15, 2028", dateSortable: 20280515, monthsOut: 20,
    noticePeriod: "12 months", noticeDeadline: "May 15, 2027",
    responsible: "Asset Manager", leaseId: "l48",
    notes: "Mid-term rent review per lease. Market rent tracking above in-place.",
    draftAction: undefined,
    status: "Pending" as const, activityLog: [],
  },

  // ── Willis Tower (cd-willis-1 through cd-willis-5) ────────────────────────
  {
    id: "cd-willis-1", asset: "Willis Tower", tenant: "United Airlines", suite: "Suite 4201",
    sf: 30000, dateType: "Expiring" as const, urgency: "Critical" as const,
    date: "Dec 31, 2026", dateSortable: 20261231, monthsOut: 3,
    noticePeriod: "12 months", noticeDeadline: "Dec 31, 2025",
    responsible: "Asset Manager", leaseId: "l51",
    notes: "Tenant evaluating HQ consolidation. Active LOI negotiations.",
    draftAction: "Draft renewal proposal",
    status: "Awaiting response" as const, activityLog: [],
  },
  {
    id: "cd-willis-2", asset: "Willis Tower", tenant: "Exelon", suite: "Suite 4001",
    sf: 28000, dateType: "Notice" as const, urgency: "Critical" as const,
    date: "Oct 15, 2026", dateSortable: 20261015, monthsOut: 1,
    noticePeriod: "6 months", noticeDeadline: "Oct 15, 2026",
    responsible: "Asset Manager", leaseId: "l52",
    notes: "Renewal notice deadline. Tenant has not confirmed intent.",
    draftAction: "Draft notice letter",
    status: "Pending" as const, activityLog: [],
  },
  {
    id: "cd-willis-3", asset: "Willis Tower", tenant: "Aon plc", suite: "Suite 3001",
    sf: 32000, dateType: "Option" as const, urgency: "Critical" as const,
    date: "Dec 1, 2026", dateSortable: 20261201, monthsOut: 3,
    noticePeriod: "9 months", noticeDeadline: "Sep 30, 2026",
    responsible: "Asset Manager", leaseId: "l54",
    notes: "Renewal option must be declared by Dec 1. Tenant requested extension.",
    draftAction: undefined,
    status: "Pending" as const, activityLog: [],
  },
  {
    id: "cd-willis-4", asset: "Willis Tower", tenant: "Abbott Laboratories", suite: "Suite 2001",
    sf: 30000, dateType: "Renewal" as const, urgency: "Upcoming" as const,
    date: "Feb 15, 2027", dateSortable: 20270215, monthsOut: 5,
    noticePeriod: "6 months", noticeDeadline: "Feb 28, 2027",
    responsible: "Asset Manager", leaseId: "l56",
    notes: "Renewal term sheet under discussion. Tenant wants cap on escalations.",
    draftAction: undefined,
    status: "Notice sent" as const, activityLog: [],
  },
  {
    id: "cd-willis-5", asset: "Willis Tower", tenant: "Tableau Software", suite: "Suite 1001",
    sf: 29000, dateType: "TI deadline" as const, urgency: "Upcoming" as const,
    date: "Jun 30, 2027", dateSortable: 20270630, monthsOut: 9,
    noticePeriod: "N/A", noticeDeadline: undefined,
    responsible: "Property Manager", leaseId: "l58",
    notes: "Tenant improvement allowance must be drawn by Jun 30, 2027 per lease.",
    draftAction: "Draft TI draw request",
    status: "Pending" as const, activityLog: [],
  },

  // ── 30 Hudson Yards (cd-hy-1 through cd-hy-4) ────────────────────────────
  {
    id: "cd-hy-1", asset: "30 Hudson Yards", tenant: "Apollo Global Mgmt", suite: "Suite 5001",
    sf: 24000, dateType: "Renewal" as const, urgency: "Monitoring" as const,
    date: "Mar 1, 2028", dateSortable: 20280301, monthsOut: 18,
    noticePeriod: "18 months", noticeDeadline: "Jun 30, 2028",
    responsible: "Asset Manager", leaseId: "l60",
    notes: "Mid-term rent review due Mar 2028. Current rent below market.",
    draftAction: undefined,
    status: "Pending" as const, activityLog: [],
  },
  {
    id: "cd-hy-2", asset: "30 Hudson Yards", tenant: "KKR & Co.", suite: "Suite 4501",
    sf: 22000, dateType: "Option" as const, urgency: "Upcoming" as const,
    date: "Jun 1, 2027", dateSortable: 20270601, monthsOut: 9,
    noticePeriod: "12 months", noticeDeadline: "Mar 31, 2029",
    responsible: "Asset Manager", leaseId: "l61",
    notes: "Expansion option exercisable Jun 2027. Floor 46 being held available.",
    draftAction: undefined,
    status: "Pending" as const, activityLog: [],
  },
  {
    id: "cd-hy-3", asset: "30 Hudson Yards", tenant: "Goldman Sachs", suite: "Suite 2001",
    sf: 24000, dateType: "Inspection" as const, urgency: "Critical" as const,
    date: "Dec 1, 2026", dateSortable: 20261201, monthsOut: 3,
    noticePeriod: "N/A", noticeDeadline: undefined,
    responsible: "Property Manager", leaseId: "l66",
    notes: "Annual HVAC and systems inspection. Coordinate with building engineer.",
    draftAction: undefined,
    status: "Pending" as const, activityLog: [],
  },
  {
    id: "cd-hy-4", asset: "30 Hudson Yards", tenant: "Meta Platforms", suite: "Suite 1501",
    sf: 23000, dateType: "Rent commencement" as const, urgency: "Critical" as const,
    date: "Jan 1, 2027", dateSortable: 20270101, monthsOut: 4,
    noticePeriod: "N/A", noticeDeadline: undefined,
    responsible: "Property Manager", leaseId: "l67",
    notes: "Year-3 rent step-up commences Jan 1. Update billing system prior.",
    draftAction: "Draft commencement letter",
    status: "Pending" as const, activityLog: [],
  },

  // ── One World Trade Center (cd-wtc-1 through cd-wtc-5) ───────────────────
  {
    id: "cd-wtc-1", asset: "One World Trade Center", tenant: "Conde Nast (WTC)", suite: "Suite 8001",
    sf: 40000, dateType: "Expiring" as const, urgency: "Upcoming" as const,
    date: "May 31, 2027", dateSortable: 20270531, monthsOut: 8,
    noticePeriod: "12 months", noticeDeadline: "May 31, 2026",
    responsible: "Asset Manager", leaseId: "l68",
    notes: "Renewal negotiation active. Tenant evaluating trophy assets in Hudson Yards.",
    draftAction: "Draft renewal proposal",
    status: "Notice sent" as const, activityLog: [],
  },
  {
    id: "cd-wtc-2", asset: "One World Trade Center", tenant: "Spotify (WTC)", suite: "Suite 7001",
    sf: 38000, dateType: "Notice" as const, urgency: "Critical" as const,
    date: "Oct 1, 2026", dateSortable: 20261001, monthsOut: 1,
    noticePeriod: "6 months", noticeDeadline: "Jul 31, 2026",
    responsible: "Asset Manager", leaseId: "l69",
    notes: "Renewal notice deadline passed. Tenant has not responded. Escalate.",
    draftAction: "Draft formal notice",
    status: "Pending" as const, activityLog: [],
  },
  {
    id: "cd-wtc-3", asset: "One World Trade Center", tenant: "Amazon Web Services", suite: "Suite 6001",
    sf: 42000, dateType: "Option" as const, urgency: "Monitoring" as const,
    date: "Apr 1, 2028", dateSortable: 20280401, monthsOut: 19,
    noticePeriod: "18 months", noticeDeadline: "Oct 1, 2028",
    responsible: "Asset Manager", leaseId: "l70",
    notes: "Expansion option for additional 20,000 SF. AWS growth trajectory strong.",
    draftAction: undefined,
    status: "Pending" as const, activityLog: [],
  },
  {
    id: "cd-wtc-4", asset: "One World Trade Center", tenant: "American Express", suite: "Suite 5001",
    sf: 40000, dateType: "Rent commencement" as const, urgency: "Critical" as const,
    date: "Dec 1, 2026", dateSortable: 20261201, monthsOut: 3,
    noticePeriod: "N/A", noticeDeadline: undefined,
    responsible: "Property Manager", leaseId: "l71",
    notes: "Year-2 rent step-up commences Dec 1. Confirm with accounts receivable.",
    draftAction: "Draft commencement letter",
    status: "Pending" as const, activityLog: [],
  },
  {
    id: "cd-wtc-5", asset: "One World Trade Center", tenant: "LinkedIn", suite: "Suite 4001",
    sf: 38000, dateType: "TI deadline" as const, urgency: "Upcoming" as const,
    date: "Feb 28, 2027", dateSortable: 20270228, monthsOut: 5,
    noticePeriod: "N/A", noticeDeadline: undefined,
    responsible: "Property Manager", leaseId: "l72",
    notes: "Remaining TI allowance of $1.2M must be drawn by Feb 28, 2027.",
    draftAction: "Draft TI draw request",
    status: "Pending" as const, activityLog: [],
  },

  // ── Transamerica Pyramid (cd-ta-1 through cd-ta-4) ────────────────────────
  {
    id: "cd-ta-1", asset: "Transamerica Pyramid", tenant: "DocuSign", suite: "Suite 2801",
    sf: 14500, dateType: "Expiring" as const, urgency: "Critical" as const,
    date: "Oct 31, 2026", dateSortable: 20261031, monthsOut: 1,
    noticePeriod: "12 months", noticeDeadline: "Oct 31, 2025",
    responsible: "Asset Manager", leaseId: "l76",
    notes: "Lease expires in 46 days. Tenant in talks but no signed LOI.",
    draftAction: "Draft holdover provision notice",
    status: "Awaiting response" as const, activityLog: [],
  },
  {
    id: "cd-ta-2", asset: "Transamerica Pyramid", tenant: "Levi Strauss", suite: "Suite 2601",
    sf: 15000, dateType: "Expiring" as const, urgency: "Critical" as const,
    date: "Dec 31, 2026", dateSortable: 20261231, monthsOut: 3,
    noticePeriod: "12 months", noticeDeadline: "Dec 31, 2025",
    responsible: "Asset Manager", leaseId: "l77",
    notes: "Tenant relocating HQ to new development in SoMa. Space goes dark Q1.",
    draftAction: "Draft vacancy marketing brief",
    status: "Notice sent" as const, activityLog: [],
  },
  {
    id: "cd-ta-3", asset: "Transamerica Pyramid", tenant: "Twitter/X (Pyramid)", suite: "Suite 2401",
    sf: 14000, dateType: "Notice" as const, urgency: "Critical" as const,
    date: "Nov 15, 2026", dateSortable: 20261115, monthsOut: 2,
    noticePeriod: "6 months", noticeDeadline: "Aug 28, 2026",
    responsible: "Asset Manager", leaseId: "l78",
    notes: "Renewal option notice window closed. Negotiate direct renewal terms.",
    draftAction: undefined,
    status: "Awaiting response" as const, activityLog: [],
  },
  {
    id: "cd-ta-4", asset: "Transamerica Pyramid", tenant: "Gap Inc.", suite: "Suite 2201",
    sf: 15500, dateType: "Option" as const, urgency: "Critical" as const,
    date: "Jan 1, 2027", dateSortable: 20270101, monthsOut: 4,
    noticePeriod: "9 months", noticeDeadline: "Jul 30, 2026",
    responsible: "Asset Manager", leaseId: "l79",
    notes: "Renewal option window. Tenant requested market comps before decision.",
    draftAction: "Draft market comparison report",
    status: "Pending" as const, activityLog: [],
  },

  // ── 200 Berkeley Street (cd-berk-1 through cd-berk-4) ────────────────────
  {
    id: "cd-berk-1", asset: "200 Berkeley Street", tenant: "Vertex Pharmaceuticals", suite: "Suite 2001",
    sf: 16000, dateType: "Expiring" as const, urgency: "Upcoming" as const,
    date: "Apr 30, 2027", dateSortable: 20270430, monthsOut: 7,
    noticePeriod: "12 months", noticeDeadline: "Apr 30, 2026",
    responsible: "Asset Manager", leaseId: "l84",
    notes: "Renewal negotiations underway. Tenant growing headcount significantly.",
    draftAction: "Draft renewal proposal",
    status: "Notice sent" as const, activityLog: [],
  },
  {
    id: "cd-berk-2", asset: "200 Berkeley Street", tenant: "Rapid7", suite: "Suite 1801",
    sf: 15500, dateType: "Notice" as const, urgency: "Critical" as const,
    date: "Dec 15, 2026", dateSortable: 20261215, monthsOut: 3,
    noticePeriod: "6 months", noticeDeadline: "Feb 28, 2027",
    responsible: "Asset Manager", leaseId: "l85",
    notes: "Notice period opens Dec 15. Tenant requested early renewal discussion.",
    draftAction: "Draft notice letter",
    status: "Pending" as const, activityLog: [],
  },
  {
    id: "cd-berk-3", asset: "200 Berkeley Street", tenant: "DraftKings", suite: "Suite 1201",
    sf: 17000, dateType: "TI deadline" as const, urgency: "Upcoming" as const,
    date: "Mar 1, 2027", dateSortable: 20270301, monthsOut: 6,
    noticePeriod: "N/A", noticeDeadline: undefined,
    responsible: "Property Manager", leaseId: "l87",
    notes: "TI allowance draw deadline. $850K remaining. Contractor on-site.",
    draftAction: "Draft TI draw request",
    status: "Pending" as const, activityLog: [],
  },
  {
    id: "cd-berk-4", asset: "200 Berkeley Street", tenant: "Biogen", suite: "Suite 0801",
    sf: 16500, dateType: "Option" as const, urgency: "Monitoring" as const,
    date: "Aug 1, 2028", dateSortable: 20280801, monthsOut: 23,
    noticePeriod: "18 months", noticeDeadline: "Feb 1, 2027",
    responsible: "Asset Manager", leaseId: "l89",
    notes: "Right of first offer on adjacent suite exercisable Aug 2028.",
    draftAction: undefined,
    status: "Pending" as const, activityLog: [],
  },

  // ── One Peachtree Center (cd-pt-1 through cd-pt-4) ───────────────────────
  {
    id: "cd-pt-1", asset: "One Peachtree Center", tenant: "Cox Enterprises", suite: "Suite 4001",
    sf: 21000, dateType: "Expiring" as const, urgency: "Upcoming" as const,
    date: "Jun 30, 2027", dateSortable: 20270630, monthsOut: 9,
    noticePeriod: "12 months", noticeDeadline: "Jun 30, 2026",
    responsible: "Asset Manager", leaseId: "l92",
    notes: "Renewal in discussion. Tenant wants 3-year short-term deal.",
    draftAction: "Draft renewal proposal",
    status: "Notice sent" as const, activityLog: [],
  },
  {
    id: "cd-pt-2", asset: "One Peachtree Center", tenant: "Equifax", suite: "Suite 3501",
    sf: 20500, dateType: "Option" as const, urgency: "Critical" as const,
    date: "Jan 15, 2027", dateSortable: 20270115, monthsOut: 4,
    noticePeriod: "9 months", noticeDeadline: "Mar 31, 2027",
    responsible: "Asset Manager", leaseId: "l93",
    notes: "Renewal option window Jan 2027. Tenant likely to exercise 5-year option.",
    draftAction: undefined,
    status: "Pending" as const, activityLog: [],
  },
  {
    id: "cd-pt-3", asset: "One Peachtree Center", tenant: "Truist Financial", suite: "Suite 1501",
    sf: 21500, dateType: "Rent commencement" as const, urgency: "Critical" as const,
    date: "Nov 1, 2026", dateSortable: 20261101, monthsOut: 2,
    noticePeriod: "N/A", noticeDeadline: undefined,
    responsible: "Property Manager", leaseId: "l97",
    notes: "Year-2 rent step-up commences Nov 1. Update billing before month end.",
    draftAction: "Draft commencement letter",
    status: "Pending" as const, activityLog: [],
  },
  {
    id: "cd-pt-4", asset: "One Peachtree Center", tenant: "Delta Air Lines", suite: "Suite 3001",
    sf: 22000, dateType: "Inspection" as const, urgency: "Upcoming" as const,
    date: "Mar 15, 2027", dateSortable: 20270315, monthsOut: 6,
    noticePeriod: "N/A", noticeDeadline: undefined,
    responsible: "Property Manager", leaseId: "l94",
    notes: "Bi-annual lease audit inspection. Coordinate with building operations.",
    draftAction: undefined,
    status: "Pending" as const, activityLog: [],
  },

  // ── Two Union Square (cd-usq-1 through cd-usq-4) ─────────────────────────
  {
    id: "cd-usq-1", asset: "Two Union Square", tenant: "Alaska Airlines", suite: "Suite 4001",
    sf: 23000, dateType: "Expiring" as const, urgency: "Critical" as const,
    date: "Dec 31, 2026", dateSortable: 20261231, monthsOut: 3,
    noticePeriod: "12 months", noticeDeadline: "Dec 31, 2025",
    responsible: "Asset Manager", leaseId: "l100",
    notes: "Renewal LOI under negotiation. Tenant wants larger footprint on Floor 40.",
    draftAction: "Draft renewal proposal",
    status: "Awaiting response" as const, activityLog: [],
  },
  {
    id: "cd-usq-2", asset: "Two Union Square", tenant: "F5 Networks", suite: "Suite 3601",
    sf: 22000, dateType: "Notice" as const, urgency: "Critical" as const,
    date: "Nov 1, 2026", dateSortable: 20261101, monthsOut: 2,
    noticePeriod: "6 months", noticeDeadline: "Oct 31, 2026",
    responsible: "Asset Manager", leaseId: "l101",
    notes: "Renewal notice deadline Nov 1. Tenant requested 30-day extension.",
    draftAction: "Draft notice letter",
    status: "Pending" as const, activityLog: [],
  },
  {
    id: "cd-usq-3", asset: "Two Union Square", tenant: "Weyerhaeuser", suite: "Suite 3201",
    sf: 24000, dateType: "Option" as const, urgency: "Upcoming" as const,
    date: "Feb 1, 2027", dateSortable: 20270201, monthsOut: 5,
    noticePeriod: "9 months", noticeDeadline: "Nov 30, 2026",
    responsible: "Asset Manager", leaseId: "l102",
    notes: "Renewal option exercisable Feb 2027. Tenant board review in Nov.",
    draftAction: undefined,
    status: "Pending" as const, activityLog: [],
  },
  {
    id: "cd-usq-4", asset: "Two Union Square", tenant: "Nordstrom", suite: "Suite 2001",
    sf: 23000, dateType: "TI deadline" as const, urgency: "Upcoming" as const,
    date: "Apr 30, 2027", dateSortable: 20270430, monthsOut: 7,
    noticePeriod: "N/A", noticeDeadline: undefined,
    responsible: "Property Manager", leaseId: "l105",
    notes: "TI allowance draw window closes Apr 30. $640K remaining undrawn.",
    draftAction: "Draft TI draw request",
    status: "Pending" as const, activityLog: [],
  },
]
