// Type is kept loose here to avoid circular dependency with stacking-plan.tsx
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const FLOORS_BY_ASSET: Record<string, any[]> = {
  "empire-state": [
    {
      number: 5,
      totalSf: 21000,
      spaces: [
        {
          suite: "500",
          sf: 21000,
          tenant: "Marsh & McLennan",
          standardizedTenant: "Marsh & McLennan",
          industry: "Professional Services",
          baseRent: 85,
          grossRent: 102,
          inPlaceRent: 89,
          lcd: "2019-03-01",
          lxd: "2029-02-28",
          expBucket: "2029",
          leaseOptions: ["Renewal Option", "Expansion Option"],
          encumbrances: [
            {
              tenant: "PwC",
              suite: "1000",
              optionType: "Expansion Option",
              priority: 1,
              details: [
                { label: "Option Type", value: "Expansion" },
                { label: "Notice Period", value: "12 months" },
                { label: "Expansion Space", value: "Floor 5 (21,000 SF)" },
                { label: "Exercise Window", value: "2027-01-01 to 2027-12-31" },
              ],
            },
          ],
        },
      ],
    },
    {
      number: 10,
      totalSf: 21500,
      spaces: [
        {
          suite: "1000",
          sf: 21500,
          tenant: "PwC",
          standardizedTenant: "PricewaterhouseCoopers",
          industry: "Professional Services",
          baseRent: 87,
          grossRent: 104,
          inPlaceRent: 91,
          lcd: "2020-06-01",
          lxd: "2030-05-31",
          expBucket: "2030",
          leaseOptions: ["Renewal Option", "ROFO"],
        },
      ],
    },
    {
      number: 12,
      totalSf: 20500,
      spaces: [
        {
          suite: "1200",
          sf: 11000,
          tenant: "Citi",
          standardizedTenant: "Citigroup",
          industry: "Financial Services",
          baseRent: 88,
          grossRent: 106,
          inPlaceRent: 92,
          lcd: "2018-09-01",
          lxd: "2027-08-31",
          expBucket: "2027",
          leaseOptions: ["Renewal Option"],
        },
        {
          suite: "1210",
          sf: 9500,
          tenant: "Apex Capital",
          standardizedTenant: "Apex Capital",
          industry: "Financial Services",
          baseRent: 86,
          grossRent: 103,
          inPlaceRent: 88,
          lcd: "2021-01-01",
          lxd: "2028-12-31",
          expBucket: "2028",
          leaseOptions: ["Renewal Option"],
        },
      ],
    },
    {
      number: 15,
      totalSf: 21000,
      spaces: [
        {
          suite: "1500",
          sf: 21000,
          tenant: "L'Oreal USA",
          standardizedTenant: "L'Oreal USA",
          industry: "Retail",
          baseRent: 90,
          grossRent: 108,
          inPlaceRent: 94,
          lcd: "2019-07-01",
          lxd: "2029-06-30",
          expBucket: "2029",
          leaseOptions: ["Renewal Option", "ROFO"],
          encumbrances: [
            {
              tenant: "Conde Nast",
              suite: "2000",
              optionType: "ROFO",
              priority: 1,
              details: [
                { label: "Option Type", value: "Right of First Offer" },
                { label: "Notice Period", value: "9 months" },
                { label: "Subject Space", value: "Suite 1500 (21,000 SF)" },
                { label: "Trigger Event", value: "Vacancy or lease expiry" },
              ],
            },
          ],
        },
      ],
    },
    {
      number: 20,
      totalSf: 21000,
      spaces: [
        {
          suite: "2000",
          sf: 21000,
          tenant: "Conde Nast",
          standardizedTenant: "Conde Nast",
          industry: "Media & Entertainment",
          baseRent: 91,
          grossRent: 109,
          inPlaceRent: 95,
          lcd: "2018-01-01",
          lxd: "2026-12-31",
          expBucket: "2026",
          leaseOptions: ["Renewal Option"],
          deals: 1,
          dealNote: "Renewal in negotiation",
        },
      ],
    },
    {
      number: 25,
      totalSf: 20000,
      spaces: [
        {
          suite: "2500",
          sf: 12500,
          tenant: "Verizon",
          standardizedTenant: "Verizon Communications",
          industry: "Technology",
          baseRent: 88,
          grossRent: 105,
          inPlaceRent: 90,
          lcd: "2021-04-01",
          lxd: "2031-03-31",
          expBucket: "2031",
          leaseOptions: ["Renewal Option", "Expansion Option"],
        },
        {
          suite: "2510",
          sf: 7500,
          listed: true,
          daysListed: 62,
          daysVacant: 62,
          expBucket: "vacant",
        },
      ],
    },
    {
      number: 28,
      totalSf: 21500,
      spaces: [
        {
          suite: "2800",
          sf: 21500,
          tenant: "KPMG",
          standardizedTenant: "KPMG",
          industry: "Professional Services",
          baseRent: 92,
          grossRent: 110,
          inPlaceRent: 96,
          lcd: "2022-01-01",
          lxd: "2032-12-31",
          expBucket: "2032",
          leaseOptions: ["Renewal Option"],
        },
      ],
    },
    {
      number: 30,
      totalSf: 21000,
      spaces: [
        {
          suite: "3000",
          sf: 21000,
          tenant: "PVH Corp",
          standardizedTenant: "PVH Corp",
          industry: "Retail",
          baseRent: 93,
          grossRent: 111,
          inPlaceRent: 97,
          lcd: "2020-10-01",
          lxd: "2028-09-30",
          expBucket: "2028",
          leaseOptions: ["Renewal Option", "ROFO"],
        },
      ],
    },
    {
      number: 31,
      totalSf: 21000,
      spaces: [
        {
          suite: "3100",
          sf: 21000,
          committedLease: true,
          committedTenant: "Ernst & Young",
          committedLcd: "2026-04-01",
          committedLxd: "2036-03-31",
          committedExpBucket: "2036",
          expBucket: "available",
          listed: true,
          daysListed: 28,
          dealNote: "Ernst & Young — LOI executed, lease in drafting",
        },
      ],
    },
    {
      number: 32,
      totalSf: 20000,
      spaces: [
        {
          suite: "3200",
          sf: 20000,
          expBucket: "available",
          listed: true,
          daysListed: 105,
          daysVacant: 105,
          internalNote: "Recently vacated by WeWork; landlord prepping TI package",
        },
      ],
    },
  ],

  salesforce: [
    {
      number: 5,
      totalSf: 20000,
      spaces: [
        {
          suite: "500",
          sf: 20000,
          tenant: "Adobe Systems",
          standardizedTenant: "Adobe Inc.",
          industry: "Technology",
          baseRent: 105,
          grossRent: 125,
          inPlaceRent: 110,
          lcd: "2020-01-01",
          lxd: "2030-12-31",
          expBucket: "2030",
          leaseOptions: ["Renewal Option", "Expansion Option"],
        },
      ],
    },
    {
      number: 10,
      totalSf: 21000,
      spaces: [
        {
          suite: "1000",
          sf: 21000,
          tenant: "Cloudflare",
          standardizedTenant: "Cloudflare Inc.",
          industry: "Technology",
          baseRent: 108,
          grossRent: 128,
          inPlaceRent: 112,
          lcd: "2021-03-01",
          lxd: "2029-02-28",
          expBucket: "2029",
          leaseOptions: ["Renewal Option"],
          encumbrances: [
            {
              tenant: "Lyft",
              suite: "1500",
              optionType: "Expansion Option",
              priority: 1,
              details: [
                { label: "Option Type", value: "Expansion" },
                { label: "Notice Period", value: "12 months" },
                { label: "Expansion Space", value: "Suite 1000 (21,000 SF)" },
                { label: "Exercise Window", value: "2026-01-01 to 2026-12-31" },
              ],
            },
          ],
        },
      ],
    },
    {
      number: 15,
      totalSf: 19500,
      spaces: [
        {
          suite: "1500",
          sf: 19500,
          tenant: "Lyft",
          standardizedTenant: "Lyft Inc.",
          industry: "Technology",
          baseRent: 110,
          grossRent: 130,
          inPlaceRent: 115,
          lcd: "2019-06-01",
          lxd: "2027-05-31",
          expBucket: "2027",
          leaseOptions: ["Renewal Option", "ROFO"],
          deals: 1,
          dealNote: "Renewal discussions ongoing",
        },
      ],
    },
    {
      number: 18,
      totalSf: 20500,
      spaces: [
        {
          suite: "1800",
          sf: 12000,
          tenant: "Stripe",
          standardizedTenant: "Stripe Inc.",
          industry: "Technology",
          baseRent: 112,
          grossRent: 132,
          inPlaceRent: 116,
          lcd: "2022-01-01",
          lxd: "2031-12-31",
          expBucket: "2031",
          leaseOptions: ["Renewal Option"],
        },
        {
          suite: "1810",
          sf: 8500,
          tenant: "Atlas Group",
          standardizedTenant: "Atlas Group",
          industry: "Financial Services",
          baseRent: 109,
          grossRent: 129,
          inPlaceRent: 113,
          lcd: "2021-07-01",
          lxd: "2028-06-30",
          expBucket: "2028",
          leaseOptions: ["Renewal Option"],
        },
      ],
    },
    {
      number: 20,
      totalSf: 21000,
      spaces: [
        {
          suite: "2000",
          sf: 21000,
          tenant: "Microsoft",
          standardizedTenant: "Microsoft Corporation",
          industry: "Technology",
          baseRent: 113,
          grossRent: 134,
          inPlaceRent: 118,
          lcd: "2020-09-01",
          lxd: "2030-08-31",
          expBucket: "2030",
          leaseOptions: ["Renewal Option", "Expansion Option"],
        },
      ],
    },
    {
      number: 22,
      totalSf: 20000,
      spaces: [
        {
          suite: "2200",
          sf: 20000,
          tenant: "Snap Inc.",
          standardizedTenant: "Snap Inc.",
          industry: "Technology",
          baseRent: 106,
          grossRent: 126,
          inPlaceRent: 110,
          lcd: "2019-01-01",
          lxd: "2026-12-31",
          expBucket: "2026",
          leaseOptions: ["Renewal Option"],
          deals: 1,
          dealNote: "Snap evaluating renewal vs. downsizing",
        },
      ],
    },
    {
      number: 24,
      totalSf: 19000,
      spaces: [
        {
          suite: "2400",
          sf: 19000,
          expBucket: "available",
          listed: true,
          daysListed: 88,
          daysVacant: 88,
          internalNote: "Uber Technologies vacated early; full floor available",
        },
      ],
    },
    {
      number: 28,
      totalSf: 20000,
      spaces: [
        {
          suite: "2800",
          sf: 20000,
          tenant: "OpenAI",
          standardizedTenant: "OpenAI",
          industry: "Technology",
          baseRent: 118,
          grossRent: 138,
          inPlaceRent: 122,
          lcd: "2023-01-01",
          lxd: "2032-12-31",
          expBucket: "2032",
          leaseOptions: ["Renewal Option", "ROFO"],
        },
      ],
    },
    {
      number: 30,
      totalSf: 19500,
      spaces: [
        {
          suite: "3000",
          sf: 19500,
          committedLease: true,
          committedTenant: "Twitter/X",
          committedLcd: "2026-06-01",
          committedLxd: "2033-05-31",
          committedExpBucket: "2033",
          expBucket: "available",
          listed: true,
          daysListed: 14,
          dealNote: "Twitter/X — lease executed, pending commencement",
        },
      ],
    },
  ],

  "one-financial": [
    {
      number: 3,
      totalSf: 8000,
      spaces: [
        {
          suite: "300",
          sf: 8000,
          tenant: "MFS Investment Management",
          standardizedTenant: "MFS Investment Management",
          industry: "Financial Services",
          baseRent: 74,
          grossRent: 89,
          inPlaceRent: 78,
          lcd: "2019-01-01",
          lxd: "2027-12-31",
          expBucket: "2027",
          leaseOptions: ["Renewal Option"],
        },
      ],
    },
    {
      number: 5,
      totalSf: 8500,
      spaces: [
        {
          suite: "500",
          sf: 8500,
          tenant: "State Street Corp",
          standardizedTenant: "State Street Corporation",
          industry: "Financial Services",
          baseRent: 78,
          grossRent: 93,
          inPlaceRent: 82,
          lcd: "2020-06-01",
          lxd: "2030-05-31",
          expBucket: "2030",
          leaseOptions: ["Renewal Option", "Expansion Option"],
          encumbrances: [
            {
              tenant: "Wellington Management",
              suite: "700",
              optionType: "Expansion Option",
              priority: 1,
              details: [
                { label: "Option Type", value: "Expansion" },
                { label: "Notice Period", value: "9 months" },
                { label: "Expansion Space", value: "Suite 500 (8,500 SF)" },
                { label: "Exercise Window", value: "2028-01-01 to 2028-06-30" },
              ],
            },
          ],
        },
      ],
    },
    {
      number: 7,
      totalSf: 7500,
      spaces: [
        {
          suite: "700",
          sf: 7500,
          tenant: "Wellington Management",
          standardizedTenant: "Wellington Management",
          industry: "Financial Services",
          baseRent: 76,
          grossRent: 91,
          inPlaceRent: 80,
          lcd: "2018-09-01",
          lxd: "2026-08-31",
          expBucket: "2026",
          leaseOptions: ["Renewal Option"],
          deals: 1,
          dealNote: "Renewal term sheet under review",
        },
      ],
    },
    {
      number: 8,
      totalSf: 8000,
      spaces: [
        {
          suite: "800",
          sf: 4500,
          tenant: "Liberty Mutual",
          standardizedTenant: "Liberty Mutual Insurance",
          industry: "Insurance",
          baseRent: 77,
          grossRent: 92,
          inPlaceRent: 81,
          lcd: "2021-01-01",
          lxd: "2029-12-31",
          expBucket: "2029",
          leaseOptions: ["Renewal Option"],
        },
        {
          suite: "810",
          sf: 3500,
          tenant: "Vertex Studios",
          standardizedTenant: "Vertex Studios",
          industry: "Technology",
          baseRent: 75,
          grossRent: 90,
          inPlaceRent: 79,
          lcd: "2022-03-01",
          lxd: "2027-02-28",
          expBucket: "2027",
          leaseOptions: ["Renewal Option"],
        },
      ],
    },
    {
      number: 9,
      totalSf: 8500,
      spaces: [
        {
          suite: "900",
          sf: 8500,
          tenant: "Putnam Investments",
          standardizedTenant: "Putnam Investments",
          industry: "Financial Services",
          baseRent: 79,
          grossRent: 94,
          inPlaceRent: 83,
          lcd: "2020-01-01",
          lxd: "2028-12-31",
          expBucket: "2028",
          leaseOptions: ["Renewal Option", "ROFO"],
        },
      ],
    },
    {
      number: 11,
      totalSf: 7000,
      spaces: [
        {
          suite: "1100",
          sf: 7000,
          expBucket: "vacant",
          listed: true,
          daysListed: 74,
          daysVacant: 74,
          internalNote: "Former Nuveen space; available immediately",
        },
      ],
    },
    {
      number: 13,
      totalSf: 8000,
      spaces: [
        {
          suite: "1300",
          sf: 8000,
          committedLease: true,
          committedTenant: "BlackRock",
          committedLcd: "2026-07-01",
          committedLxd: "2033-06-30",
          committedExpBucket: "2033",
          expBucket: "available",
          listed: true,
          daysListed: 21,
          dealNote: "BlackRock — lease signed, construction underway",
        },
      ],
    },
    {
      number: 15,
      totalSf: 8500,
      spaces: [
        {
          suite: "1500",
          sf: 8500,
          tenant: "Fidelity Investments",
          standardizedTenant: "Fidelity Investments",
          industry: "Financial Services",
          baseRent: 82,
          grossRent: 97,
          inPlaceRent: 86,
          lcd: "2021-10-01",
          lxd: "2031-09-30",
          expBucket: "2031",
          leaseOptions: ["Renewal Option", "Expansion Option"],
        },
      ],
    },
  ],

  willis: [
    {
      number: 5,
      totalSf: 30000,
      spaces: [
        {
          suite: "500",
          sf: 30000,
          tenant: "Grainger",
          standardizedTenant: "W.W. Grainger Inc.",
          industry: "Professional Services",
          baseRent: 60,
          grossRent: 73,
          inPlaceRent: 63,
          lcd: "2019-04-01",
          lxd: "2029-03-31",
          expBucket: "2029",
          leaseOptions: ["Renewal Option", "Expansion Option"],
        },
      ],
    },
    {
      number: 10,
      totalSf: 29000,
      spaces: [
        {
          suite: "1000",
          sf: 16000,
          tenant: "Exelon",
          standardizedTenant: "Exelon Corporation",
          industry: "Energy",
          baseRent: 62,
          grossRent: 75,
          inPlaceRent: 65,
          lcd: "2020-01-01",
          lxd: "2028-12-31",
          expBucket: "2028",
          leaseOptions: ["Renewal Option"],
        },
        {
          suite: "1010",
          sf: 13000,
          tenant: "Bluewave LLC",
          standardizedTenant: "Bluewave LLC",
          industry: "Technology",
          baseRent: 59,
          grossRent: 72,
          inPlaceRent: 62,
          lcd: "2022-06-01",
          lxd: "2027-05-31",
          expBucket: "2027",
          leaseOptions: ["Renewal Option"],
        },
      ],
    },
    {
      number: 15,
      totalSf: 31000,
      spaces: [
        {
          suite: "1500",
          sf: 31000,
          tenant: "Hyatt Hotels",
          standardizedTenant: "Hyatt Hotels Corporation",
          industry: "Professional Services",
          baseRent: 63,
          grossRent: 76,
          inPlaceRent: 66,
          lcd: "2018-07-01",
          lxd: "2026-06-30",
          expBucket: "2026",
          leaseOptions: ["Renewal Option", "ROFO"],
          deals: 1,
          dealNote: "Hyatt evaluating renewal; competing bids at 150 N Riverside",
        },
      ],
    },
    {
      number: 20,
      totalSf: 30000,
      spaces: [
        {
          suite: "2000",
          sf: 30000,
          tenant: "Aon plc",
          standardizedTenant: "Aon plc",
          industry: "Insurance",
          baseRent: 64,
          grossRent: 77,
          inPlaceRent: 67,
          lcd: "2021-01-01",
          lxd: "2031-12-31",
          expBucket: "2031",
          leaseOptions: ["Renewal Option", "Expansion Option"],
          encumbrances: [
            {
              tenant: "United Airlines",
              suite: "2500",
              optionType: "ROFO",
              priority: 1,
              details: [
                { label: "Option Type", value: "Right of First Offer" },
                { label: "Notice Period", value: "12 months" },
                { label: "Subject Space", value: "Suite 2000 (30,000 SF)" },
                { label: "Trigger Event", value: "Lease expiry or early surrender" },
              ],
            },
          ],
        },
      ],
    },
    {
      number: 25,
      totalSf: 28000,
      spaces: [
        {
          suite: "2500",
          sf: 28000,
          tenant: "United Airlines",
          standardizedTenant: "United Airlines",
          industry: "Transportation",
          baseRent: 65,
          grossRent: 78,
          inPlaceRent: 68,
          lcd: "2019-10-01",
          lxd: "2030-09-30",
          expBucket: "2030",
          leaseOptions: ["Renewal Option"],
        },
      ],
    },
    {
      number: 30,
      totalSf: 30000,
      spaces: [
        {
          suite: "3000",
          sf: 18000,
          tenant: "Kraft Heinz",
          standardizedTenant: "The Kraft Heinz Company",
          industry: "Retail",
          baseRent: 64,
          grossRent: 77,
          inPlaceRent: 67,
          lcd: "2020-04-01",
          lxd: "2027-03-31",
          expBucket: "2027",
          leaseOptions: ["Renewal Option"],
        },
        {
          suite: "3010",
          sf: 12000,
          expBucket: "available",
          listed: true,
          daysListed: 117,
          daysVacant: 117,
          internalNote: "Tableau Software LOI expired; relisting at reduced ask",
        },
      ],
    },
    {
      number: 35,
      totalSf: 29000,
      spaces: [
        {
          suite: "3500",
          sf: 29000,
          tenant: "Abbott Laboratories",
          standardizedTenant: "Abbott Laboratories",
          industry: "Healthcare",
          baseRent: 66,
          grossRent: 79,
          inPlaceRent: 69,
          lcd: "2022-01-01",
          lxd: "2032-12-31",
          expBucket: "2032",
          leaseOptions: ["Renewal Option", "ROFO"],
        },
      ],
    },
    {
      number: 40,
      totalSf: 31000,
      spaces: [
        {
          suite: "4000",
          sf: 31000,
          committedLease: true,
          committedTenant: "Notion Labs",
          committedLcd: "2026-10-01",
          committedLxd: "2033-09-30",
          committedExpBucket: "2033",
          expBucket: "available",
          listed: true,
          daysListed: 9,
          dealNote: "Notion Labs — LOI executed, term sheet finalized",
        },
      ],
    },
    {
      number: 42,
      totalSf: 30000,
      spaces: [
        {
          suite: "4200",
          sf: 30000,
          tenant: "Tableau Software",
          standardizedTenant: "Tableau Software",
          industry: "Technology",
          baseRent: 70,
          grossRent: 83,
          inPlaceRent: 73,
          lcd: "2021-07-01",
          lxd: "2029-06-30",
          expBucket: "2029",
          leaseOptions: ["Renewal Option", "Expansion Option"],
        },
      ],
    },
  ],

  "hudson-yards": [
    {
      number: 5,
      totalSf: 24000,
      spaces: [
        {
          suite: "500",
          sf: 24000,
          tenant: "Wells Fargo",
          standardizedTenant: "Wells Fargo & Company",
          industry: "Financial Services",
          baseRent: 108,
          grossRent: 130,
          inPlaceRent: 113,
          lcd: "2020-01-01",
          lxd: "2030-12-31",
          expBucket: "2030",
          leaseOptions: ["Renewal Option", "Expansion Option"],
        },
      ],
    },
    {
      number: 10,
      totalSf: 23500,
      spaces: [
        {
          suite: "1000",
          sf: 23500,
          tenant: "Deutsche Bank",
          standardizedTenant: "Deutsche Bank AG",
          industry: "Financial Services",
          baseRent: 110,
          grossRent: 132,
          inPlaceRent: 115,
          lcd: "2019-07-01",
          lxd: "2029-06-30",
          expBucket: "2029",
          leaseOptions: ["Renewal Option"],
          encumbrances: [
            {
              tenant: "KKR & Co.",
              suite: "1500",
              optionType: "Expansion Option",
              priority: 1,
              details: [
                { label: "Option Type", value: "Expansion" },
                { label: "Notice Period", value: "18 months" },
                { label: "Expansion Space", value: "Suite 1000 (23,500 SF)" },
                { label: "Exercise Window", value: "2027-07-01 to 2028-06-30" },
              ],
            },
          ],
        },
      ],
    },
    {
      number: 15,
      totalSf: 25000,
      spaces: [
        {
          suite: "1500",
          sf: 25000,
          tenant: "KKR & Co.",
          standardizedTenant: "KKR & Co. Inc.",
          industry: "Financial Services",
          baseRent: 115,
          grossRent: 138,
          inPlaceRent: 120,
          lcd: "2021-01-01",
          lxd: "2031-12-31",
          expBucket: "2031",
          leaseOptions: ["Renewal Option", "ROFO"],
        },
      ],
    },
    {
      number: 20,
      totalSf: 24000,
      spaces: [
        {
          suite: "2000",
          sf: 24000,
          tenant: "Blackstone",
          standardizedTenant: "Blackstone Inc.",
          industry: "Financial Services",
          baseRent: 118,
          grossRent: 141,
          inPlaceRent: 123,
          lcd: "2020-04-01",
          lxd: "2028-03-31",
          expBucket: "2028",
          leaseOptions: ["Renewal Option", "Expansion Option"],
        },
      ],
    },
    {
      number: 25,
      totalSf: 23000,
      spaces: [
        {
          suite: "2500",
          sf: 23000,
          tenant: "Apollo Global Management",
          standardizedTenant: "Apollo Global Management",
          industry: "Financial Services",
          baseRent: 120,
          grossRent: 143,
          inPlaceRent: 125,
          lcd: "2022-01-01",
          lxd: "2032-12-31",
          expBucket: "2032",
          leaseOptions: ["Renewal Option"],
        },
      ],
    },
    {
      number: 30,
      totalSf: 24500,
      spaces: [
        {
          suite: "3000",
          sf: 24500,
          tenant: "Citi Private Bank",
          standardizedTenant: "Citigroup Private Bank",
          industry: "Financial Services",
          baseRent: 117,
          grossRent: 140,
          inPlaceRent: 122,
          lcd: "2019-10-01",
          lxd: "2027-09-30",
          expBucket: "2027",
          leaseOptions: ["Renewal Option"],
          deals: 1,
          dealNote: "Citi evaluating expansion to Floor 35",
        },
      ],
    },
    {
      number: 35,
      totalSf: 25000,
      spaces: [
        {
          suite: "3500",
          sf: 13000,
          tenant: "Bluewave LLC",
          standardizedTenant: "Bluewave LLC",
          industry: "Technology",
          baseRent: 112,
          grossRent: 134,
          inPlaceRent: 117,
          lcd: "2023-01-01",
          lxd: "2030-12-31",
          expBucket: "2030",
          leaseOptions: ["Renewal Option"],
        },
        {
          suite: "3510",
          sf: 12000,
          expBucket: "available",
          listed: true,
          daysListed: 44,
          daysVacant: 44,
          internalNote: "Contiguous with Suite 3500; ideal for Citi expansion",
        },
      ],
    },
    {
      number: 40,
      totalSf: 24000,
      spaces: [
        {
          suite: "4000",
          sf: 24000,
          tenant: "Goldman Sachs",
          standardizedTenant: "Goldman Sachs Group",
          industry: "Financial Services",
          baseRent: 122,
          grossRent: 145,
          inPlaceRent: 127,
          lcd: "2023-06-01",
          lxd: "2033-05-31",
          expBucket: "2033",
          executedDeal: true,
          leaseOptions: ["Renewal Option", "Expansion Option"],
        },
      ],
    },
    {
      number: 45,
      totalSf: 22000,
      spaces: [
        {
          suite: "4500",
          sf: 22000,
          committedLease: true,
          committedTenant: "Stripe",
          committedLcd: "2026-09-01",
          committedLxd: "2034-08-31",
          committedExpBucket: "2034",
          expBucket: "available",
          listed: true,
          daysListed: 6,
          dealNote: "Stripe — lease in final review",
        },
      ],
    },
    {
      number: 50,
      totalSf: 22000,
      spaces: [
        {
          suite: "5000",
          sf: 22000,
          tenant: "Meta Platforms",
          standardizedTenant: "Meta Platforms Inc.",
          industry: "Technology",
          baseRent: 125,
          grossRent: 148,
          inPlaceRent: 130,
          lcd: "2023-09-01",
          lxd: "2033-08-31",
          expBucket: "2033",
          executedDeal: true,
          leaseOptions: ["Renewal Option"],
        },
      ],
    },
  ],

  "one-wtc": [
    {
      number: 10,
      totalSf: 40000,
      spaces: [
        {
          suite: "1000",
          sf: 40000,
          tenant: "American Express",
          standardizedTenant: "American Express Company",
          industry: "Financial Services",
          baseRent: 78,
          grossRent: 94,
          inPlaceRent: 82,
          lcd: "2019-06-01",
          lxd: "2029-05-31",
          expBucket: "2029",
          leaseOptions: ["Renewal Option", "Expansion Option"],
        },
      ],
    },
    {
      number: 20,
      totalSf: 40000,
      spaces: [
        {
          suite: "2000",
          sf: 40000,
          tenant: "Conde Nast",
          standardizedTenant: "Conde Nast",
          industry: "Media & Entertainment",
          baseRent: 82,
          grossRent: 98,
          inPlaceRent: 86,
          lcd: "2018-01-01",
          lxd: "2031-12-31",
          expBucket: "2031",
          leaseOptions: ["Renewal Option", "ROFO"],
          encumbrances: [
            {
              tenant: "Spotify",
              suite: "2800",
              optionType: "ROFO",
              priority: 1,
              details: [
                { label: "Option Type", value: "Right of First Offer" },
                { label: "Notice Period", value: "12 months" },
                { label: "Subject Space", value: "Suite 2000 (40,000 SF)" },
                { label: "Trigger Event", value: "Lease expiry or surrender" },
              ],
            },
          ],
        },
      ],
    },
    {
      number: 28,
      totalSf: 39000,
      spaces: [
        {
          suite: "2800",
          sf: 39000,
          tenant: "Spotify",
          standardizedTenant: "Spotify Technology",
          industry: "Technology",
          baseRent: 80,
          grossRent: 96,
          inPlaceRent: 84,
          lcd: "2020-09-01",
          lxd: "2028-08-31",
          expBucket: "2028",
          leaseOptions: ["Renewal Option"],
          deals: 1,
          dealNote: "Spotify reviewing expansion to Floor 35",
        },
      ],
    },
    {
      number: 35,
      totalSf: 41000,
      spaces: [
        {
          suite: "3500",
          sf: 41000,
          tenant: "LinkedIn",
          standardizedTenant: "LinkedIn Corporation",
          industry: "Technology",
          baseRent: 84,
          grossRent: 100,
          inPlaceRent: 88,
          lcd: "2021-03-01",
          lxd: "2030-02-28",
          expBucket: "2030",
          leaseOptions: ["Renewal Option", "Expansion Option"],
        },
      ],
    },
    {
      number: 40,
      totalSf: 40000,
      spaces: [
        {
          suite: "4000",
          sf: 22000,
          tenant: "Amazon Web Services",
          standardizedTenant: "Amazon Web Services",
          industry: "Technology",
          baseRent: 85,
          grossRent: 101,
          inPlaceRent: 89,
          lcd: "2022-01-01",
          lxd: "2032-12-31",
          expBucket: "2032",
          leaseOptions: ["Renewal Option"],
        },
        {
          suite: "4010",
          sf: 18000,
          tenant: "Apex Capital",
          standardizedTenant: "Apex Capital",
          industry: "Financial Services",
          baseRent: 82,
          grossRent: 98,
          inPlaceRent: 86,
          lcd: "2021-10-01",
          lxd: "2026-09-30",
          expBucket: "2026",
          leaseOptions: ["Renewal Option"],
          deals: 1,
          dealNote: "Apex renewal under negotiation",
        },
      ],
    },
    {
      number: 50,
      totalSf: 40000,
      spaces: [
        {
          suite: "5000",
          sf: 40000,
          tenant: "Cloudflare",
          standardizedTenant: "Cloudflare Inc.",
          industry: "Technology",
          baseRent: 87,
          grossRent: 104,
          inPlaceRent: 91,
          lcd: "2023-01-01",
          lxd: "2033-12-31",
          expBucket: "2033",
          leaseOptions: ["Renewal Option"],
        },
      ],
    },
    {
      number: 60,
      totalSf: 38000,
      spaces: [
        {
          suite: "6000",
          sf: 38000,
          committedLease: true,
          committedTenant: "ByteDance",
          committedLcd: "2026-11-01",
          committedLxd: "2034-10-31",
          committedExpBucket: "2034",
          expBucket: "available",
          listed: true,
          daysListed: 18,
          dealNote: "ByteDance — lease in drafting, pending regulatory clearance",
        },
      ],
    },
    {
      number: 70,
      totalSf: 39000,
      spaces: [
        {
          suite: "7000",
          sf: 39000,
          tenant: "Meta Platforms",
          standardizedTenant: "Meta Platforms Inc.",
          industry: "Technology",
          baseRent: 90,
          grossRent: 107,
          inPlaceRent: 94,
          lcd: "2022-06-01",
          lxd: "2031-05-31",
          expBucket: "2031",
          leaseOptions: ["Renewal Option", "ROFO"],
        },
      ],
    },
    {
      number: 80,
      totalSf: 40000,
      spaces: [
        {
          suite: "8000",
          sf: 40000,
          expBucket: "vacant",
          listed: true,
          daysListed: 156,
          daysVacant: 156,
          internalNote: "Dropbox early termination; full floor available with Hudson views",
        },
      ],
    },
  ],

  transamerica: [
    {
      number: 5,
      totalSf: 15500,
      spaces: [
        {
          suite: "500",
          sf: 15500,
          tenant: "Charles Schwab",
          standardizedTenant: "Charles Schwab Corporation",
          industry: "Financial Services",
          baseRent: 90,
          grossRent: 108,
          inPlaceRent: 95,
          lcd: "2019-09-01",
          lxd: "2027-08-31",
          expBucket: "2027",
          leaseOptions: ["Renewal Option"],
        },
      ],
    },
    {
      number: 10,
      totalSf: 15000,
      spaces: [
        {
          suite: "1000",
          sf: 15000,
          tenant: "Gap Inc.",
          standardizedTenant: "Gap Inc.",
          industry: "Retail",
          baseRent: 92,
          grossRent: 110,
          inPlaceRent: 97,
          lcd: "2020-03-01",
          lxd: "2028-02-29",
          expBucket: "2028",
          leaseOptions: ["Renewal Option", "ROFO"],
          encumbrances: [
            {
              tenant: "DocuSign",
              suite: "1500",
              optionType: "Expansion Option",
              priority: 1,
              details: [
                { label: "Option Type", value: "Expansion" },
                { label: "Notice Period", value: "12 months" },
                { label: "Expansion Space", value: "Suite 1000 (15,000 SF)" },
                { label: "Exercise Window", value: "2026-03-01 to 2026-08-31" },
              ],
            },
          ],
        },
      ],
    },
    {
      number: 15,
      totalSf: 15000,
      spaces: [
        {
          suite: "1500",
          sf: 15000,
          tenant: "DocuSign",
          standardizedTenant: "DocuSign Inc.",
          industry: "Technology",
          baseRent: 95,
          grossRent: 114,
          inPlaceRent: 100,
          lcd: "2021-01-01",
          lxd: "2029-12-31",
          expBucket: "2029",
          leaseOptions: ["Renewal Option", "Expansion Option"],
        },
      ],
    },
    {
      number: 18,
      totalSf: 14500,
      spaces: [
        {
          suite: "1800",
          sf: 14500,
          tenant: "Ripple Labs",
          standardizedTenant: "Ripple Labs",
          industry: "Technology",
          baseRent: 96,
          grossRent: 115,
          inPlaceRent: 101,
          lcd: "2022-07-01",
          lxd: "2027-06-30",
          expBucket: "2027",
          leaseOptions: ["Renewal Option"],
          deals: 1,
          dealNote: "Ripple Labs evaluating downsizing at renewal",
        },
      ],
    },
    {
      number: 20,
      totalSf: 14000,
      spaces: [
        {
          suite: "2000",
          sf: 8000,
          tenant: "Levi Strauss",
          standardizedTenant: "Levi Strauss & Co.",
          industry: "Retail",
          baseRent: 94,
          grossRent: 113,
          inPlaceRent: 99,
          lcd: "2019-01-01",
          lxd: "2026-12-31",
          expBucket: "2026",
          leaseOptions: ["Renewal Option"],
        },
        {
          suite: "2010",
          sf: 6000,
          tenant: "Fidelity Investments",
          standardizedTenant: "Fidelity Investments",
          industry: "Financial Services",
          baseRent: 93,
          grossRent: 111,
          inPlaceRent: 98,
          lcd: "2021-04-01",
          lxd: "2028-03-31",
          expBucket: "2028",
          leaseOptions: ["Renewal Option"],
        },
      ],
    },
    {
      number: 22,
      totalSf: 14000,
      spaces: [
        {
          suite: "2200",
          sf: 14000,
          tenant: "First Republic",
          standardizedTenant: "First Republic Bank",
          industry: "Financial Services",
          baseRent: 97,
          grossRent: 116,
          inPlaceRent: 102,
          lcd: "2020-09-01",
          lxd: "2030-08-31",
          expBucket: "2030",
          leaseOptions: ["Renewal Option", "ROFO"],
        },
      ],
    },
    {
      number: 24,
      totalSf: 13500,
      spaces: [
        {
          suite: "2400",
          sf: 13500,
          committedLease: true,
          committedTenant: "Dropbox Inc.",
          committedLcd: "2026-08-01",
          committedLxd: "2033-07-31",
          committedExpBucket: "2033",
          expBucket: "available",
          listed: true,
          daysListed: 33,
          dealNote: "Dropbox Inc. — lease signed, pending buildout",
        },
      ],
    },
    {
      number: 26,
      totalSf: 13000,
      spaces: [
        {
          suite: "2600",
          sf: 13000,
          tenant: "Twitter/X",
          standardizedTenant: "X Corp.",
          industry: "Technology",
          baseRent: 100,
          grossRent: 119,
          inPlaceRent: 105,
          lcd: "2021-10-01",
          lxd: "2029-09-30",
          expBucket: "2029",
          leaseOptions: ["Renewal Option"],
        },
      ],
    },
    {
      number: 28,
      totalSf: 13000,
      spaces: [
        {
          suite: "2800",
          sf: 13000,
          expBucket: "vacant",
          listed: true,
          daysListed: 93,
          daysVacant: 93,
          internalNote: "Morningstar Inc. sublease expired; direct vacancy",
        },
      ],
    },
  ],

  "200-berkeley": [
    {
      number: 3,
      totalSf: 16000,
      spaces: [
        {
          suite: "300",
          sf: 16000,
          tenant: "Acadian Asset Management",
          standardizedTenant: "Acadian Asset Management",
          industry: "Financial Services",
          baseRent: 84,
          grossRent: 100,
          inPlaceRent: 88,
          lcd: "2020-01-01",
          lxd: "2028-12-31",
          expBucket: "2028",
          leaseOptions: ["Renewal Option"],
        },
      ],
    },
    {
      number: 5,
      totalSf: 17500,
      spaces: [
        {
          suite: "500",
          sf: 17500,
          tenant: "Liberty Mutual",
          standardizedTenant: "Liberty Mutual Insurance",
          industry: "Insurance",
          baseRent: 86,
          grossRent: 103,
          inPlaceRent: 90,
          lcd: "2019-06-01",
          lxd: "2029-05-31",
          expBucket: "2029",
          leaseOptions: ["Renewal Option", "Expansion Option"],
          encumbrances: [
            {
              tenant: "Biogen",
              suite: "800",
              optionType: "Expansion Option",
              priority: 1,
              details: [
                { label: "Option Type", value: "Expansion" },
                { label: "Notice Period", value: "12 months" },
                { label: "Expansion Space", value: "Suite 500 (17,500 SF)" },
                { label: "Exercise Window", value: "2027-06-01 to 2027-12-31" },
              ],
            },
          ],
        },
      ],
    },
    {
      number: 8,
      totalSf: 16000,
      spaces: [
        {
          suite: "800",
          sf: 16000,
          tenant: "Biogen",
          standardizedTenant: "Biogen Inc.",
          industry: "Healthcare",
          baseRent: 88,
          grossRent: 105,
          inPlaceRent: 92,
          lcd: "2021-03-01",
          lxd: "2031-02-28",
          expBucket: "2031",
          leaseOptions: ["Renewal Option", "ROFO"],
        },
      ],
    },
    {
      number: 10,
      totalSf: 17000,
      spaces: [
        {
          suite: "1000",
          sf: 9500,
          tenant: "DraftKings",
          standardizedTenant: "DraftKings Inc.",
          industry: "Technology",
          baseRent: 87,
          grossRent: 104,
          inPlaceRent: 91,
          lcd: "2022-01-01",
          lxd: "2028-12-31",
          expBucket: "2028",
          leaseOptions: ["Renewal Option"],
        },
        {
          suite: "1010",
          sf: 7500,
          tenant: "Morningstar Inc.",
          standardizedTenant: "Morningstar Inc.",
          industry: "Financial Services",
          baseRent: 85,
          grossRent: 102,
          inPlaceRent: 89,
          lcd: "2021-09-01",
          lxd: "2027-08-31",
          expBucket: "2027",
          leaseOptions: ["Renewal Option"],
          deals: 1,
          dealNote: "Morningstar renewal discussions initiated",
        },
      ],
    },
    {
      number: 12,
      totalSf: 16500,
      spaces: [
        {
          suite: "1200",
          sf: 16500,
          tenant: "Rapid7",
          standardizedTenant: "Rapid7 Inc.",
          industry: "Technology",
          baseRent: 89,
          grossRent: 106,
          inPlaceRent: 93,
          lcd: "2020-09-01",
          lxd: "2026-08-31",
          expBucket: "2026",
          leaseOptions: ["Renewal Option"],
          deals: 1,
          dealNote: "Rapid7 exploring relocation; watching market",
        },
      ],
    },
    {
      number: 15,
      totalSf: 17000,
      spaces: [
        {
          suite: "1500",
          sf: 17000,
          tenant: "Vertex Pharmaceuticals",
          standardizedTenant: "Vertex Pharmaceuticals",
          industry: "Healthcare",
          baseRent: 92,
          grossRent: 110,
          inPlaceRent: 96,
          lcd: "2021-01-01",
          lxd: "2032-12-31",
          expBucket: "2032",
          leaseOptions: ["Renewal Option", "Expansion Option"],
        },
      ],
    },
    {
      number: 18,
      totalSf: 16000,
      spaces: [
        {
          suite: "1800",
          sf: 16000,
          committedLease: true,
          committedTenant: "Wayfair Inc.",
          committedLcd: "2026-12-01",
          committedLxd: "2034-11-30",
          committedExpBucket: "2034",
          expBucket: "available",
          listed: true,
          daysListed: 45,
          dealNote: "Wayfair Inc. — lease in final negotiation",
        },
      ],
    },
    {
      number: 20,
      totalSf: 15000,
      spaces: [
        {
          suite: "2000",
          sf: 15000,
          expBucket: "vacant",
          listed: true,
          daysListed: 81,
          daysVacant: 81,
          internalNote: "Brightcove relocated HQ; full floor available with TI allowance",
        },
      ],
    },
  ],

  peachtree: [
    {
      number: 5,
      totalSf: 21000,
      spaces: [
        {
          suite: "500",
          sf: 21000,
          tenant: "Cox Enterprises",
          standardizedTenant: "Cox Enterprises",
          industry: "Media & Entertainment",
          baseRent: 46,
          grossRent: 56,
          inPlaceRent: 49,
          lcd: "2019-01-01",
          lxd: "2029-12-31",
          expBucket: "2029",
          leaseOptions: ["Renewal Option", "ROFO"],
        },
      ],
    },
    {
      number: 10,
      totalSf: 22000,
      spaces: [
        {
          suite: "1000",
          sf: 22000,
          tenant: "Truist Financial",
          standardizedTenant: "Truist Financial Corporation",
          industry: "Financial Services",
          baseRent: 48,
          grossRent: 58,
          inPlaceRent: 51,
          lcd: "2020-06-01",
          lxd: "2028-05-31",
          expBucket: "2028",
          leaseOptions: ["Renewal Option"],
          encumbrances: [
            {
              tenant: "Invesco",
              suite: "1500",
              optionType: "ROFO",
              priority: 1,
              details: [
                { label: "Option Type", value: "Right of First Offer" },
                { label: "Notice Period", value: "9 months" },
                { label: "Subject Space", value: "Suite 1000 (22,000 SF)" },
                { label: "Trigger Event", value: "Tenant vacates or lease expires" },
              ],
            },
          ],
        },
      ],
    },
    {
      number: 15,
      totalSf: 21000,
      spaces: [
        {
          suite: "1500",
          sf: 21000,
          tenant: "Invesco",
          standardizedTenant: "Invesco Ltd.",
          industry: "Financial Services",
          baseRent: 50,
          grossRent: 60,
          inPlaceRent: 53,
          lcd: "2021-01-01",
          lxd: "2030-12-31",
          expBucket: "2030",
          leaseOptions: ["Renewal Option", "Expansion Option"],
        },
      ],
    },
    {
      number: 20,
      totalSf: 22000,
      spaces: [
        {
          suite: "2000",
          sf: 12000,
          tenant: "Equifax",
          standardizedTenant: "Equifax Inc.",
          industry: "Technology",
          baseRent: 49,
          grossRent: 59,
          inPlaceRent: 52,
          lcd: "2018-10-01",
          lxd: "2026-09-30",
          expBucket: "2026",
          leaseOptions: ["Renewal Option"],
          deals: 1,
          dealNote: "Equifax renewal under review",
        },
        {
          suite: "2010",
          sf: 10000,
          tenant: "Tableau Software",
          standardizedTenant: "Tableau Software",
          industry: "Technology",
          baseRent: 47,
          grossRent: 57,
          inPlaceRent: 50,
          lcd: "2021-07-01",
          lxd: "2027-06-30",
          expBucket: "2027",
          leaseOptions: ["Renewal Option"],
        },
      ],
    },
    {
      number: 25,
      totalSf: 21000,
      spaces: [
        {
          suite: "2500",
          sf: 21000,
          tenant: "Delta Air Lines",
          standardizedTenant: "Delta Air Lines Inc.",
          industry: "Transportation",
          baseRent: 51,
          grossRent: 61,
          inPlaceRent: 54,
          lcd: "2020-01-01",
          lxd: "2031-12-31",
          expBucket: "2031",
          leaseOptions: ["Renewal Option"],
        },
      ],
    },
    {
      number: 30,
      totalSf: 22000,
      spaces: [
        {
          suite: "3000",
          sf: 22000,
          tenant: "GE Digital",
          standardizedTenant: "GE Digital",
          industry: "Technology",
          baseRent: 52,
          grossRent: 62,
          inPlaceRent: 55,
          lcd: "2022-03-01",
          lxd: "2029-02-28",
          expBucket: "2029",
          leaseOptions: ["Renewal Option", "Expansion Option"],
        },
      ],
    },
    {
      number: 35,
      totalSf: 21000,
      spaces: [
        {
          suite: "3500",
          sf: 21000,
          committedLease: true,
          committedTenant: "NCR Corporation",
          committedLcd: "2026-10-01",
          committedLxd: "2033-09-30",
          committedExpBucket: "2033",
          expBucket: "available",
          listed: true,
          daysListed: 27,
          dealNote: "NCR Corporation — LOI executed, lease in preparation",
        },
      ],
    },
    {
      number: 40,
      totalSf: 21000,
      spaces: [
        {
          suite: "4000",
          sf: 21000,
          expBucket: "vacant",
          listed: true,
          daysListed: 142,
          daysVacant: 142,
          internalNote: "Norfolk Southern relocated; full floor with parking rights available",
        },
      ],
    },
  ],

  "union-square": [
    {
      number: 5,
      totalSf: 23000,
      spaces: [
        {
          suite: "500",
          sf: 23000,
          tenant: "Nordstrom",
          standardizedTenant: "Nordstrom Inc.",
          industry: "Retail",
          baseRent: 57,
          grossRent: 69,
          inPlaceRent: 60,
          lcd: "2019-04-01",
          lxd: "2027-03-31",
          expBucket: "2027",
          leaseOptions: ["Renewal Option"],
          deals: 1,
          dealNote: "Nordstrom renewal discussions early stage",
        },
      ],
    },
    {
      number: 10,
      totalSf: 24000,
      spaces: [
        {
          suite: "1000",
          sf: 24000,
          tenant: "Weyerhaeuser",
          standardizedTenant: "Weyerhaeuser Company",
          industry: "Professional Services",
          baseRent: 59,
          grossRent: 71,
          inPlaceRent: 62,
          lcd: "2020-01-01",
          lxd: "2029-12-31",
          expBucket: "2029",
          leaseOptions: ["Renewal Option", "ROFO"],
          encumbrances: [
            {
              tenant: "F5 Networks",
              suite: "1500",
              optionType: "Expansion Option",
              priority: 1,
              details: [
                { label: "Option Type", value: "Expansion" },
                { label: "Notice Period", value: "12 months" },
                { label: "Expansion Space", value: "Suite 1000 (24,000 SF)" },
                { label: "Exercise Window", value: "2028-01-01 to 2028-06-30" },
              ],
            },
          ],
        },
      ],
    },
    {
      number: 15,
      totalSf: 22000,
      spaces: [
        {
          suite: "1500",
          sf: 22000,
          tenant: "F5 Networks",
          standardizedTenant: "F5 Inc.",
          industry: "Technology",
          baseRent: 61,
          grossRent: 73,
          inPlaceRent: 64,
          lcd: "2021-07-01",
          lxd: "2031-06-30",
          expBucket: "2031",
          leaseOptions: ["Renewal Option", "Expansion Option"],
        },
      ],
    },
    {
      number: 20,
      totalSf: 24000,
      spaces: [
        {
          suite: "2000",
          sf: 24000,
          tenant: "Alaska Airlines",
          standardizedTenant: "Alaska Airlines",
          industry: "Transportation",
          baseRent: 62,
          grossRent: 74,
          inPlaceRent: 65,
          lcd: "2019-10-01",
          lxd: "2028-09-30",
          expBucket: "2028",
          leaseOptions: ["Renewal Option"],
        },
      ],
    },
    {
      number: 24,
      totalSf: 23000,
      spaces: [
        {
          suite: "2400",
          sf: 23000,
          tenant: "Expeditors International",
          standardizedTenant: "Expeditors International",
          industry: "Transportation",
          baseRent: 60,
          grossRent: 72,
          inPlaceRent: 63,
          lcd: "2020-06-01",
          lxd: "2026-05-31",
          expBucket: "2026",
          leaseOptions: ["Renewal Option"],
          deals: 1,
          dealNote: "Expeditors lease expiring; renewal or relocation TBD",
        },
      ],
    },
    {
      number: 28,
      totalSf: 22500,
      spaces: [
        {
          suite: "2800",
          sf: 12000,
          tenant: "T-Mobile",
          standardizedTenant: "T-Mobile US",
          industry: "Technology",
          baseRent: 63,
          grossRent: 75,
          inPlaceRent: 66,
          lcd: "2022-01-01",
          lxd: "2030-12-31",
          expBucket: "2030",
          leaseOptions: ["Renewal Option"],
        },
        {
          suite: "2810",
          sf: 10500,
          tenant: "Notion Labs",
          standardizedTenant: "Notion Labs",
          industry: "Technology",
          baseRent: 62,
          grossRent: 74,
          inPlaceRent: 65,
          lcd: "2023-01-01",
          lxd: "2028-12-31",
          expBucket: "2028",
          leaseOptions: ["Renewal Option"],
        },
      ],
    },
    {
      number: 32,
      totalSf: 23000,
      spaces: [
        {
          suite: "3200",
          sf: 23000,
          committedLease: true,
          committedTenant: "Fidelity Investments",
          committedLcd: "2026-09-01",
          committedLxd: "2034-08-31",
          committedExpBucket: "2034",
          expBucket: "available",
          listed: true,
          daysListed: 12,
          dealNote: "Fidelity Investments — LOI signed, lease in drafting",
        },
      ],
    },
    {
      number: 36,
      totalSf: 22000,
      spaces: [
        {
          suite: "3600",
          sf: 22000,
          tenant: "REI Co-op",
          standardizedTenant: "REI Co-op",
          industry: "Retail",
          baseRent: 65,
          grossRent: 77,
          inPlaceRent: 68,
          lcd: "2021-04-01",
          lxd: "2029-03-31",
          expBucket: "2029",
          leaseOptions: ["Renewal Option", "ROFO"],
        },
      ],
    },
    {
      number: 40,
      totalSf: 22000,
      spaces: [
        {
          suite: "4000",
          sf: 22000,
          tenant: "Morningstar Inc.",
          standardizedTenant: "Morningstar Inc.",
          industry: "Financial Services",
          baseRent: 66,
          grossRent: 78,
          inPlaceRent: 69,
          lcd: "2022-09-01",
          lxd: "2032-08-31",
          expBucket: "2032",
          leaseOptions: ["Renewal Option"],
        },
      ],
    },
  ],
}
