const L = "/vts_lookfeel_nav_concept_1-0/logos/"

export const TENANT_LOGO: Record<string, string> = {
  // Original set
  "Starbucks Corporation":    `${L}starbucks.png`,
  "Pfizer Inc.":              `${L}pfizer.png`,
  "Morgan Stanley":           `${L}morganstanley.png`,
  "Deloitte LLP":             `${L}deloitte.png`,
  "KPMG":                     `${L}kpmg.png`,
  "Ernst & Young":            `${L}ey.png`,
  "HSBC Holdings":            `${L}hsbc.png`,
  "Latham & Watkins":         `${L}lw.png`,
  "JPMorgan Chase":           `${L}jpmorgan.png`,
  "Amazon.com":               `${L}amazon.png`,
  "WeWork":                   `${L}wework.png`,
  "Google LLC":               `${L}google.png`,
  "Tesla Inc.":               `${L}tesla.png`,
  "Cisco Systems":            `${L}cisco.png`,
  "Salesforce Inc.":          `${L}salesforce.png`,
  "BlackRock":                `${L}blackrock.png`,
  "Goldman Sachs":            `${L}goldmansachs.png`,
  "McKinsey & Co.":           `${L}mckinsey.png`,
  "Spotify":                  `${L}spotify.png`,
  "Airbnb":                   `${L}airbnb.png`,
  "Stripe":                   `${L}stripe.png`,
  "Twitter/X":                `${L}x.png`,
  "Uber Technologies":        `${L}uber.png`,
  "Microsoft":                `${L}microsoft.png`,
  "Meta Platforms":           `${L}meta.png`,
  // d31-d37
  "Dropbox Inc.":             `${L}dropbox.png`,
  "Notion Labs":              `${L}notion.png`,
  "Morningstar Inc.":         `${L}morningstar.png`,
  "Fidelity Investments":     `${L}fidelity.png`,
  "Tableau Software":         `${L}tableau.png`,
  "NCR Corporation":          `${L}ncr.png`,
  "Wayfair Inc.":             `${L}wayfair.png`,
  // d38-d42 VTS Tower HQ
  "Accenture":                `${L}accenture.png`,
  "Hogan Lovells":            `${L}hoganlovells.png`,
  "Boston Consulting Grp":    `${L}bcg.png`,
  "Workday Inc.":             `${L}workday.png`,
  "Palantir Technologies":    `${L}palantir.png`,
  // d43-d49 Empire State
  "Verizon":                  `${L}verizon.png`,
  "PVH Corp":                 `${L}pvh.png`,
  "Citi":                     `${L}citi.png`,
  "Marsh & McLennan":         `${L}mmc.png`,
  "PwC":                      `${L}pwc.png`,
  "L'Oreal USA":              `${L}loreal.png`,
  "Conde Nast":               `${L}condenast.png`,
  // d50-d54 Salesforce Tower
  "Lyft":                     `${L}lyft.png`,
  "Adobe Systems":            `${L}adobe.png`,
  "Snap Inc.":                `${L}snap.png`,
  "OpenAI":                   `${L}openai.png`,
  "Cloudflare":               `${L}cloudflare.png`,
  // d55-d61 One Financial Plaza
  "State Street Corp":        `${L}statestreet.png`,
  "Liberty Mutual":           `${L}libertymutual.png`,
  "John Hancock":             `${L}johnhancock.png`,
  "Putnam Investments":       `${L}putnam.png`,
  "Wellington Mgmt":          `${L}wellington.png`,
  "MFS Investment Mgmt":      `${L}mfs.png`,
  "Nuveen":                   `${L}nuveen.png`,
  // d62-d68 Willis Tower
  "United Airlines":          `${L}united.png`,
  "Exelon":                   `${L}exelon.png`,
  "Hyatt Hotels":             `${L}hyatt.png`,
  "Aon plc":                  `${L}aon.png`,
  "Kraft Heinz":              `${L}kraftheinz.png`,
  "Abbott Laboratories":      `${L}abbott.png`,
  "Grainger":                 `${L}grainger.png`,
  // d69-d74 30 Hudson Yards
  "Apollo Global Mgmt":       `${L}apollo.png`,
  "KKR & Co.":                `${L}kkr.png`,
  "Blackstone":               `${L}blackstone.png`,
  "Citi Private Bank":        `${L}citi.png`,
  "Deutsche Bank":            `${L}deutschebank.png`,
  "Wells Fargo":              `${L}wellsfargo.png`,
  // d75-d81 One World Trade Center
  "Conde Nast (WTC)":         `${L}condenast.png`,
  "Spotify (WTC)":            `${L}spotify.png`,
  "Amazon Web Services":      `${L}amazon.png`,
  "American Express":         `${L}amex.png`,
  "LinkedIn":                 `${L}linkedin.png`,
  "ByteDance":                `${L}bytedance.png`,
  "Cloudflare (WTC)":         `${L}cloudflare.png`,
  // d82-d88 Transamerica Pyramid
  "DocuSign":                 `${L}docusign.png`,
  "Levi Strauss":             `${L}levistrauss.png`,
  "Twitter/X (Pyramid)":      `${L}x.png`,
  "Gap Inc.":                 `${L}gap.png`,
  "Charles Schwab":           `${L}schwab.png`,
  "First Republic":           `${L}johnhancock.png`,
  "Ripple Labs":              `${L}ripple.png`,
  // d89-d95 200 Berkeley Street
  "Vertex Pharmaceuticals":   `${L}vertexpharma.png`,
  "Rapid7":                   `${L}rapid7.png`,
  "Brightcove":               `${L}brightcove.png`,
  "DraftKings":               `${L}draftkings.png`,
  "Liberty Mutual (Berk)":    `${L}libertymutual.png`,
  "Biogen":                   `${L}biogen.png`,
  "Acadian Asset Mgmt":       `${L}statestreet.png`,
  // d96-d102 One Peachtree Center
  "Cox Enterprises":          `${L}cox.png`,
  "Equifax":                  `${L}equifax.png`,
  "Delta Air Lines":          `${L}delta.png`,
  "Invesco":                  `${L}invesco.png`,
  "Norfolk Southern":         `${L}norfolksouthern.png`,
  "Truist Financial":         `${L}truist.png`,
  "GE Digital":               `${L}ge.png`,
  // d103-d109 Two Union Square
  "Alaska Airlines":          `${L}alaskaair.png`,
  "F5 Networks":              `${L}f5.png`,
  "Weyerhaeuser":             `${L}weyerhaeuser.png`,
  "Expeditors Intl":          `${L}expeditors.png`,
  "T-Mobile":                 `${L}tmobile.png`,
  "Nordstrom":                `${L}nordstrom.png`,
  "REI Co-op":                `${L}rei.png`,
}

export const TENANT_DOMAIN: Record<string, string> = {
  // Stacking plan / options & rights tenants
  "Starbucks Corporation":         "starbucks.com",
  "Pfizer Inc.":                   "pfizer.com",
  "Pfizer":                        "pfizer.com",
  "Morgan Stanley":                "morganstanley.com",
  "Deloitte LLP":                  "deloitte.com",
  "KPMG":                          "kpmg.com",
  "Ernst & Young":                 "ey.com",
  "HSBC Holdings":                 "hsbc.com",
  "Latham & Watkins":              "lw.com",
  "JPMorgan Chase":                "jpmorgan.com",
  "Amazon.com Inc.":               "amazon.com",
  "Blackstone Inc.":               "blackstone.com",
  "Sullivan & Cromwell LLP":       "sullcrom.com",
  "The Carlyle Group Inc.":        "carlyle.com",
  "CVS Health Corporation":        "cvshealth.com",
  "Skadden Arps":                  "skadden.com",
  "Citigroup":                     "citi.com",
  "Blackrock":                     "blackrock.com",
  // d00–d30
  "Amazon.com":               "amazon.com",
  "Meridian Health":          "meridianhealth.com",
  "WeWork":                   "wework.com",
  "Google LLC":               "google.com",
  "Tesla Inc.":               "tesla.com",
  "Cisco Systems":            "cisco.com",
  "Salesforce Inc.":          "salesforce.com",
  "BlackRock":                "blackrock.com",
  "Goldman Sachs":            "goldmansachs.com",
  "McKinsey & Co.":           "mckinsey.com",
  "Spotify":                  "spotify.com",
  "Airbnb":                   "airbnb.com",
  "Stripe":                   "stripe.com",
  "Twitter/X":                "x.com",
  "Uber Technologies":        "uber.com",
  "Microsoft":                "microsoft.com",
  "Meta Platforms":           "meta.com",
  // d31–d37
  "Dropbox Inc.":             "dropbox.com",
  "Notion Labs":              "notion.so",
  "Morningstar Inc.":         "morningstar.com",
  "Fidelity Investments":     "fidelity.com",
  "Tableau Software":         "tableau.com",
  "NCR Corporation":          "ncr.com",
  "Wayfair Inc.":             "wayfair.com",
  // d38–d42 VTS Tower HQ
  "Accenture":                "accenture.com",
  "Hogan Lovells":            "hoganlovells.com",
  "Boston Consulting Grp":    "bcg.com",
  "Workday Inc.":             "workday.com",
  "Palantir Technologies":    "palantir.com",
  // d43–d49 Empire State
  "Verizon":                  "verizon.com",
  "PVH Corp":                 "pvh.com",
  "Citi":                     "citi.com",
  "Marsh & McLennan":         "mmc.com",
  "PwC":                      "pwc.com",
  "L'Oreal USA":              "loreal.com",
  "Conde Nast":               "condenast.com",
  // d50–d54 Salesforce Tower
  "Lyft":                     "lyft.com",
  "Adobe Systems":            "adobe.com",
  "Snap Inc.":                "snap.com",
  "OpenAI":                   "openai.com",
  "Cloudflare":               "cloudflare.com",
  // d55–d61 One Financial Plaza
  "State Street Corp":        "statestreet.com",
  "Liberty Mutual":           "libertymutual.com",
  "John Hancock":             "johnhancock.com",
  "Putnam Investments":       "putnam.com",
  "Wellington Mgmt":          "wellington.com",
  "MFS Investment Mgmt":      "mfs.com",
  "Nuveen":                   "nuveen.com",
  // d62–d68 Willis Tower
  "United Airlines":          "united.com",
  "Exelon":                   "exelon.com",
  "Hyatt Hotels":             "hyatt.com",
  "Aon plc":                  "aon.com",
  "Kraft Heinz":              "kraftheinz.com",
  "Abbott Laboratories":      "abbott.com",
  "Grainger":                 "grainger.com",
  // d69–d74 30 Hudson Yards
  "Apollo Global Mgmt":       "apollo.com",
  "KKR & Co.":                "kkr.com",
  "Blackstone":               "blackstone.com",
  "Citi Private Bank":        "citi.com",
  "Deutsche Bank":            "db.com",
  "Wells Fargo":              "wellsfargo.com",
  // d75–d81 One World Trade Center
  "Conde Nast (WTC)":         "condenast.com",
  "Spotify (WTC)":            "spotify.com",
  "Amazon Web Services":      "amazon.com",
  "American Express":         "americanexpress.com",
  "LinkedIn":                 "linkedin.com",
  "ByteDance":                "bytedance.com",
  "Cloudflare (WTC)":         "cloudflare.com",
  // d82–d88 Transamerica Pyramid
  "DocuSign":                 "docusign.com",
  "Levi Strauss":             "levistrauss.com",
  "Twitter/X (Pyramid)":      "x.com",
  "Gap Inc.":                 "gap.com",
  "Charles Schwab":           "schwab.com",
  "First Republic":           "firstrepublic.com",
  "Ripple Labs":              "ripple.com",
  // d89–d95 200 Berkeley Street
  "Vertex Pharmaceuticals":   "vrtx.com",
  "Rapid7":                   "rapid7.com",
  "Brightcove":               "brightcove.com",
  "DraftKings":               "draftkings.com",
  "Liberty Mutual (Berk)":    "libertymutual.com",
  "Biogen":                   "biogen.com",
  "Acadian Asset Mgmt":       "acadian-asset.com",
  // d96–d102 One Peachtree Center
  "Cox Enterprises":          "cox.com",
  "Equifax":                  "equifax.com",
  "Delta Air Lines":          "delta.com",
  "Invesco":                  "invesco.com",
  "Norfolk Southern":         "nscorp.com",
  "Truist Financial":         "truist.com",
  "GE Digital":               "ge.com",
  // d103–d109 Two Union Square
  "Alaska Airlines":          "alaskaair.com",
  "F5 Networks":              "f5.com",
  "Weyerhaeuser":             "weyerhaeuser.com",
  "Expeditors Intl":          "expeditors.com",
  "T-Mobile":                 "t-mobile.com",
  "Nordstrom":                "nordstrom.com",
  "REI Co-op":                "rei.com",
}
